apiVersion: v1
kind: RoleBinding
metadata:
  name: view
roleRef:
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: demo-istio
userNames:
- system:serviceaccount:demo-istio:default