service:
  say:
    name: ${say-service.endpoint}
    path: /say
opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-collector.istio-system.svc:14268/api/traces
    service-name: frontend
    enabled: true
    enable-b3-propagation: true
    log-spans: true