server.port: ${say-service.port}

service:
  greeting:
    name: ${greeting-service.endpoint}
    path: /greeting

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-collector.istio-system.svc:14268/api/traces
    service-name: say-service
    enabled: true
    enable-b3-propagation: true
    log-spans: true