---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: greeting-service
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: me.snowdrop
  name: greeting-service
spec:
  replicas: 1
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      labels:
        app: greeting-service
        provider: fabric8
        version: 1.0-SNAPSHOT
        group: me.snowdrop
    spec:
      containers:
      - image: greeting-service:latest
        imagePullPolicy: Always
        name: spring-boot
