server.port: ${greeting-service.port}
opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-collector.istio-system.svc:14268/api/traces
    service-name: greeting-service
    enabled: true
    enable-b3-propagation: true
    log-spans: true